#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx should be listening on port 80
# When querying Nginx at its root /
# with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!
sudo apt-get update
sudo apt-get install -y nginx
echo "<html><body>Hello World!</body></html>" | sudo tee /var/www/html/index.html
sudo service nginx restart
