#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#   - Enables management via the init script.
#   - Distributes requests using a round-robin algorithm.
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get update
apt-get install -y haproxy=2.8.*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen charef.tech
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 421972-web-01 54.87.205.91:80 check
    server 421972-web-02 54.87.240.9:80 check
EOT

service haproxy start
