#!/usr/bin/env bash
# A script to configure HAproxy on load balancer server

# Install HAProxy
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

# Configure HAProxy
# Define the frontend and backend configuration
frontend_config="frontend charef.tech\n\ttimeout client 30000\n\tbind *:80\n\tmode http\n\tdefault_backend charef.tech_backend"
backend_config="backend charef.tech_backend\n\ttimeout connect 3000\n\ttimeout server 30000\n\tbalance roundrobin\n\tserver 421972-web-01 54.87.205.91 check\n\tserver 421972-web-02 54.87.240.9 check"

# Stop HAProxy service before making changes to haproxy.cfg
sudo service haproxy stop

# Add the frontend and backend configuration to the existing HAProxy configuration
sudo bash -c "echo -e '$frontend_config' >> /etc/haproxy/haproxy.cfg"
sudo bash -c "echo -e '$backend_config' >> /etc/haproxy/haproxy.cfg"

# Enable HAproxy using init
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy services
sudo service haproxy restart
