#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.
if [ $# -eq 1 ]
then
	the_ip="$1"
	ping -c 5 "$the_ip"
else
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
fi
