#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
cut -d ':' -f 1,3,6 /etc/passwd | while IFS=':' read -r username userid homepath; do
    echo "$username:$userid:$homepath"
done
