#!/usr/bin/env bash
#script that gives you information about the school file.
while IFS=':' read -r username x userid groupid x homepath shell; do
    echo "The user $username is part of the $groupid gang, lives in $homepath and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd

