#!/usr/bin/env bash
#script that displays Bad luck at 4, good luck at 8, best school otherwise.
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
