#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key is protected by the passphrase betty
# Generate RSA key pair
key_name="school"
ssh-keygen -t rsa -b 4096 -f "$key_name" -N "betty"

echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $key_name."
echo "Your public key has been saved in ${key_name}.pub."

# Display the key fingerprint
echo "The key fingerprint is:"
ssh-keygen -lf "${key_name}.pub"

# Display the key's randomart image
echo "The key's randomart image is:"
ssh-keygen -lvf "${key_name}.pub"
