#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key is protected by the passphrase betty
ssh-keygen -t rsa -b 4096 -f ~/alx-system_engineering-devops/0x0B-ssh/school -N "betty"

echo "Generating public/private rsa key pair."
echo "Your identification has been saved in school."
echo "Your public key has been saved in school.pub."
echo "The key fingerprint is:"
ssh-keygen -lf "school.pub"
echo "The key's randomart image is:"
ssh-keygen -lvf "school.pub"
